name 'kuali-exports'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures kuali-exports'
long_description 'Installs/Configures kuali-exports'
version '0.1.0'
depends 'nfs'
