name 'kuali-tools'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures kuali-tools'
long_description 'Installs/Configures kuali-tools'
version '0.1.0'
depends 'aws'
depends 'docker'
