name 'kuali-tags'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures kuali-tags'
long_description 'Installs/Configures kuali-tags'
version '0.1.0'
depends 'aws'
